### ISSUE TITLE
import path error?

### ISSUE THREAD

**Issue by jspeis** [georgeOsdDev/react-fileupload-progress#10]
When I tried to import FileUploadProgress as follows:
`    import FileUploadProgress  from 'fileUploadProgress';
`
... like the example in the README, I would get an error:
`    Module not found: Error: Cannot resolve module 'fileUploadProgress' in
`

What did work for me was using:
`    import FileUploadProgress  from 'react-fileupload-progress/lib/index';
`

I had installed using the example npm command.

**Comment by georgeOsdDev** [comment]
I've updated `README`
Please use `import FileUploadProgress from 'react-fileupload-progress';`

**Comment by epaulson** [comment]
The example on http://georgeosddev.github.io/react-fileupload-progress/ is still with the old module name

**Comment by georgeOsdDev** [comment]
Thanks.
Gh-pages regenerated.

https://github.com/georgeOsdDev/react-fileupload-progress/commit/fe4e98e2e3d6bdbd5174704659d83d2b177b2b6e
