### ISSUE TITLE
Can't get example to run

### ISSUE THREAD

**Issue by jcrain** [georgeOsdDev/react-fileupload-progress#19]
`import React from 'react/addons';` yields `Error: Cannot find module 'react/addons'` when running the example. 

Changing `import React from 'react/addons';` to `import React from 'react/addons';` gets rid of the addon error but yields `Uncaught TypeError: _react2.default.render is not a function`

I was able to use the component in my react project, this seems to just be an issue with the implementation in the example.

**Comment by georgeOsdDev** [comment]
@jcrain 

I've fixed example please check latest master branch.
Thanks!
