### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by raminahmadi1986** [georgeOsdDev/react-fileupload-progress#22]
Hi
how can I add custom header values ? ( for authorization and ... )

**Comment by georgeOsdDev** [comment]
You can use `props.beforeSend`

```
myBeforeSend = (req) => {
  req.setRequestHeader('myHeader', 'myVal')
  return req
}
```

https://github.com/georgeOsdDev/react-fileupload-progress/blob/master/src/components/FileUploadProgress.js#L152
