### ISSUE TITLE
What to do if 2 or more file upload is needed on a single form?

### ISSUE THREAD

**Issue by doppelgunner** [georgeOsdDev/react-fileupload-progress#27]
Example one for profile pic (image) and the other is for resume (pdf). How to use onsubmit file? 

additional info: Im currently using form data and multer library to get the files from the request.
TIA!

**Comment by georgeOsdDev** [comment]
You can use 2way,

1. write your own `formRenderer ` with 2 or more `<input type='file'/>`

2. append extra files with `formCustomizer`.
