### ISSUE TITLE
How to use with text fields and other input controls?

### ISSUE THREAD

**Issue by doppelgunner** [georgeOsdDev/react-fileupload-progress#28]
Example the upload field is not required and it still should submit the form, the problem is how to do that with the react-fileupload-progress. Im having problem calling the onSubmit of the FormRenderer if together with other input fields.

**Comment by georgeOsdDev** [comment]
Could you try like below.
This form will contain `myTextInput`.
```
  customFormRenderer(onSubmit){
    return (
      <form id='customForm' style={{marginBottom: '15px'}}>
        <label style={styles.bslabel} htmlFor="exampleInputFile">File input</label>
        <input style={{display: 'block'}} type="file" name='file' id="exampleInputFile" />
       
        <input type="text" key='myTextInput' name='myTextInput'/>       

        <p style={styles.bsHelp}>This is custom form.</p>
        <button type="button" style={styles.bsButton} onClick={onSubmit}>Upload</button>
      </form>
    );
  }
```

**Comment by adueck** [comment]
@doppelgunner  I am also having trouble calling `onSubmit` when using the `customFormRenderer` as used in the example.

If I use `FileUploadProgress` without a `formRenderer` or `formGetter` it works great and uploads the file. But as soon as I add the `formRenderer` and `formGetter` (exactly as in the example), the Upload button doesn't submit anymore. Can you please provide a detailed example of the whole thing with a custom text field? (not just the one function above)

**Comment by adueck** [comment]
When this form is submitted and the file is uploaded, where is the value for `myTextInput` available?

I can't find it and it seems that `formGetter` just returns and empty object in this part of the example.

```
  formGetter(){
    return new FormData(document.getElementById('customForm'));
  }
```
