### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by KyleAMathews** [georgeOsdDev/react-fileupload-progress#4]
`formRnederer` is used throughout the code + documentation. I'm assuming that's a typo?

**Comment by georgeOsdDev** [comment]
@KyleAMathews 

Thanks feedback.
Fixed with
https://github.com/georgeOsdDev/react-fileupload-progress/commit/798ca47601c8c29a6b7c5dc405a7183d17d4bd4b

And V0.2.0 is now released.

**Comment by KyleAMathews** [comment]
👍
