### ISSUE TITLE
How to view uploaded file

### ISSUE THREAD

**Issue by ikashifullah** [georgeOsdDev/react-fileupload-progress#41]
Hi @georgeOsdDev,

 Is there anyway to view the uploaded file? I can't figure it out.

**Comment by georgeOsdDev** [comment]
This component is client side library for wrapping `XMLHttpRequest`.
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequestEventTarget/onprogress
So uploaded files are not in the scope of this component.

You need to use your own server api like `GET /path/to/api/files` to get list of uploaded files.
